# Translations template for magnum.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the magnum project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: magnum 2015.1.1.dev100\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-05-28 09:18+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: magnum/api/middleware/parsable_error.py:77
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: magnum/cmd/conductor.py:56
#, python-format
msgid ""
"The Heat template can not be found for either k8s atomic "
"%(atomic_template)s or coreos (coreos_template)%s. Install template first"
" if you want to create bay."
msgstr ""

#: magnum/common/exception.py:128
#, python-format
msgid "%(correlation_id)s:%(excp)s"
msgstr ""

#: magnum/common/exception.py:216
msgid "Exception in string format operation"
msgstr ""

#: magnum/common/exception.py:218
#, python-format
msgid "%(name)s: %(value)s"
msgstr ""

#: magnum/common/magnum_keystoneclient.py:89
msgid "Admin client authentication failed"
msgstr ""

#: magnum/common/magnum_keystoneclient.py:119
msgid "Unknown version in auth_token_info"
msgstr ""

#: magnum/common/magnum_keystoneclient.py:125
msgid "Keystone v3 API connection failed, no password trust or auth_token!"
msgstr ""

#: magnum/common/magnum_keystoneclient.py:136
msgid "trust token re-scoping failed!"
msgstr ""

#: magnum/common/utils.py:397
#, python-format
msgid "Could not remove tmpdir: %s"
msgstr ""

#: magnum/common/utils.py:428
#, python-format
msgid "Failed to make file system. File system %s is not supported."
msgstr ""

#: magnum/common/utils.py:432
#, python-format
msgid "Failed to create a file system in %(path)s. Error: %(error)s"
msgstr ""

#: magnum/conductor/handlers/bay_conductor.py:234
#, python-format
msgid "Unable to create bay, stack_id: %(stack_id)s, reason: %(reason)s"
msgstr ""

#: magnum/conductor/handlers/bay_conductor.py:240
#, python-format
msgid "Unable to delete bay, stack_id: %(stack_id)s, reason: %(reason)s"
msgstr ""

#: magnum/conductor/handlers/bay_conductor.py:246
#, python-format
msgid "Unable to update bay, stack_id: %(stack_id)s, reason: %(reason)s"
msgstr ""

#: magnum/conductor/handlers/bay_conductor.py:257
#: magnum/conductor/handlers/bay_conductor.py:265
#, python-format
msgid ""
"Bay check exit after %(attempts)s attempts,stack_id: %(id)s, "
"stack_status: %(status)s"
msgstr ""

#: magnum/conductor/handlers/docker_conductor.py:64
#, python-format
msgid "Error while connect to docker container %(name)s: %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:89
#, python-format
msgid "Couldn't create service with contents %(content)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:103
#, python-format
msgid "Couldn't update service with contents %(content)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:117
#, python-format
msgid "Couldn't delete service %(service)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:131
#, python-format
msgid "Couldn't create pod with contents %(content)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:145
#, python-format
msgid "Couldn't update pod with %(content)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:156
#, python-format
msgid "Couldn't delete pod %(pod)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:177
#, python-format
msgid "Couldn't create rc with contents %(content)s due error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:190
#, python-format
msgid "Couldn't update rc with contents %(content)s due to error %(error)s"
msgstr ""

#: magnum/conductor/handlers/common/kube_utils.py:203
#, python-format
msgid "Couldn't delete rc %(rc)s due to error %(error)s"
msgstr ""

#: magnum/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: magnum/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: magnum/openstack/common/periodic_task.py:228
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: magnum/openstack/common/service.py:272
msgid "Unhandled exception"
msgstr ""

